# This file is used to manually point to inventory STATIONXML files
#
# For the channel level arguments (example, CHA), the 2 element list needs to contain the following in the correct order:
# [path to the folder containing the inventory files, inventory file name]
#
# This will be considered when iris_compatible is set to False in a callPycheronMetric config
# IMPORTANT: THIS CONFIG FILE IS NOT NEEDED WHEN USING 'wfdb' IN CALLPYCHERON, 'wfdb' WILL KNOW WHERE TO GET FILES
#
# IMPORTANT: IF USING THIS FEATURE, INFORMATION FOR EVERY NETWORK/STATION/LOCATION/CHANNEL MUST BE PROVIDED
#
# Example, where NE is network, STTN is station, -- is location, and CHA is channel
# [NE]
#   [NE.STTN]
#     [NE.STTN.--]
#       CHA = ["/path/to/resp/folder", "NESTTNCHA.xml"]